### ISSUE TITLE
Review metadata-related components

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#142]
Review metadata-related components for consistency and good naming practices.

### nc:MetadataType

A data type for information that further qualifies primary data; data about data.

1. Use "Metadata" as the class term
2. Sort elements alphabetically

- nc:CaveatText
- nc:AdministrativeID
- nc:DistributionText
- nc:EffectiveDate
- nc:ExpirationDate
- nc:LastUpdatedDate
- nc:LastVerifiedDate
- nc:ProbabilityPercent
- nc:QualityComment
- nc:ConfidencePercent
- nc:ReportedDate
- nc:ReportingOrganizationText
- nc:ReportingPersonRoleText
- nc:ReportingPersonText
- nc:SensitivityText
- nc:CreatorName
- nc:DescriptionText
- nc:SourceIDText
- nc:SourceContactPersonText
- nc:PublisherName
- nc:ReleaseDate
- nc:RepositoryID
- nc:SourceText
- nc:LanguageAbstract
- nc:Comment

### cbrn:TotalDoseMetadataType

A data type for metadata about TotalDose data.

- cbrn:RadRawTotalDoseValue
- cbrn:RadDetectorInformation

### cbrn:TotalExposureMetadataType

A data type for metadata about TotalExposure data.

- cbrn:RadDetectorInformation
- cbrn:RadRawTotalExposureValue

### hs:MetadataType

A data type for metadata about a record.

- hs:CreationDate
- hs:LastUpdatedTrackingID
- hs:ProtectedHealthInformationIndicator
- hs:SubmissionDateTime

### j:JusticeMetadataType

A data type for information that further qualifies the kind of data represented.

- j:CriminalInformationIndicator
- j:IntelligenceInformationIndicator

*Remove "Justice" from the name?*

### scr:PersonMetadataType

A data type for metadata about the data associated with a person being screened.

- scr:ConfidenceLevel (scr:ConfidenceLevelType) - A classification of the reliability of the PERSON ALERT.
- scr:PersonConfidenceLevelPercent (niem-xs:decimal) - A Quantitative based on the number of encounters. Measured as an overall percentage.

**Comment by DonClysdale** [comment]
At ESDC, we had a couple pieces of Metadata that were not easy to implement using the MetadataType - sort:direction (used on requests payloads and response payloads) and a sort:order number to maintain order across model transformations. We implemented them using attributes on structures:SimpleObjectAttributeGroup by defining their namespace as "urn:us:gov:ic:ism". This allows schema validation of those attributes in a certain context (e.g. creating a unique constraint on that element within a specific element) which would not be possible using the MetadataType constructs. Simple attributes also allow XPath selection (filtering) and simple XSLT sorting.

In some cases (e.g. document management system) the MetadataType and structures:metadata approach works well (many pieces of unique metadata about one thing, e.g. document). In other cases, the processing required to use simple metadata about any element become onerous and inhibits simple implementation of filtering and sorting of the data.

Possible solution?
In niem/utility implement a new schema (metadata.xsd) for metadata attributes and allow simple attribute-only metadata to be added in the namespace say "http://release.niem.gov/niem/metadata/5.0/" with namespace prefix "metadata" and add that "metadata" namespace to namespace list in structures:SimpleObjectAttributeGroup. Note that cleanup of structures.xsd needed to use structures:SimpleObjectAttributeGroup in all type definitions - so that even Metadata can have Metadata.

Examples of some simple attributes could be a subset of the Metadata elements that can logically only occur once and would be useful for filtering and sorting:
- any data processing information describing how the data is presented (e.g. sortDirection, sortOrder)
- any dates related to currency of the information which could be used to filter the data (e.g. createdDate,lastUpdatedDate,...)
- any security or sensitivity information that could be used to redact (filter) the data - like the IC Trusted Data Format already enabled by the urn:us:gov:ic:ism and urn:us:gov:ic:ntk namespaces.

Schema developers could add their own extension(s) with the metadata namespace to add additional attributes between NIEM major versions.

**Comment by bdhandspicker** [comment]
The NTAC is reworking MetadataType as part of it's 5.0 metamodeling work. Anything beyond re-aligning names should probably be kicked over the wall to NTAC.

**Comment by bdhandspicker** [comment]
Don, could you provide NTAC with an example?

**Comment by DonClysdale** [comment]
[metadata.zip](https://github.com/NIEM/NIEM-Releases/files/4445873/metadata.zip)

Here is an example of change to structures.xsd, new metadata.xsd and an nc:Document with four nc:DocumentContentListText that have metadata attributes (as allowed by metadata.xsd) that can be easily used to filter content. Same as currently an attribute from IC Trusted Data Format schemas (IC-ISM.xsd or IC-NTK.xsd) can be used to filter elements for example to redact elements where ism:classification="TS" (redact elements that are Top Secret).

**Comment by DonClysdale** [comment]
Brian,

Attached is an example of change to structures.xsd, new metadata.xsd and an example nc:Document with four nc:DocumentContentListText that have metadata attributes (as allowed by metadata.xsd) that can be easily used to filter content. Same as currently an attribute from IC Trusted Data Format schemas (IC-ISM.xsd or IC-NTK.xsd) can be used to filter elements for example to redact elements where ism:classification="TS" (redact elements that are Top Secret).

Don

**Comment by webb** [comment]
The example that was provided was a proposed revision to NIEM, rather than an example of what NIEM can't do. The NTAC discussed the topics in this issue. 

- the NTAC does not embrace a method that involves overriding contents of a namespace, such as the “metadata” namespace that @DonClysdale proposed.. 
- This use case can be handled by either (1) adding desired attributes to the appropriate types as extensions, or (2) adding content as elements as augmentations, or (3) using the existing `structures:metadata` method for adding content
- The NTAC does not want to introduce more wildcards into the NIEM release without very concrete, specific requirements. The ISM requirements that introduced the `xs:anyAttribute` in structures was to achieve a very specific requirement.

**Comment by cdmgtri** [comment]
The Harmonization Workgroup recommends using class term "Metadata".
