### ISSUE TITLE
Add Controlled Unclassified Information (CUI) metadata

### ISSUE THREAD

**Issue by cdmgtri** [NIEM/NIEM-Releases#156]
Controlled Unclassified Information (CUI) is information that requires safeguarding or dissemination controls pursuant to and consistent with applicable law, regulations, and government-wide policies but is not classified under Executive Order 13526 or the Atomic Energy Act, as amended.  This release includes metadata tags for approved CUI Categories and Limited Dissemination Control markings found on the CUI Registry (https://www.archives.gov/cui).

**Comment by myergens** [comment]
I have a few questions that I hope you can answer:

1. Are there any guides or examples for use of the CUI metadata (such as which elements are required, which are optional)?
2. Have Schematron rules been defined for CUI banners and portion marking?

Thank you for your time.
Sincerely,
David Yergensen [michael.d.yergensen@nasa.gov]

**Comment by cdmgtri** [comment]
Hi David,

Re 1: There are currently no NIEM-specific examples of how to use CUI markings with NIEM, but the CUI Marking Handbook and 32 CFR Part 2002 include instructions for CUI markings.  These resources were used in developing the NIEM CUI content and are available [here](https://www.archives.gov/cui).

Re 2: Schematron rules for CUI banner and portion markings do not exist yet, but they have been discussed.

## Additional resources

- [General training info about metadata in NIEM](https://niem.github.io/reference/concepts/metadata/)
- [XML-specific information about metadata in NIEM](https://niem.github.io/reference/concepts/metadata/xml/) 
- [Link to the NIEM 5.0 cui schema](https://raw.githubusercontent.com/NIEM/NIEM-Releases/niem-5.0/xsd/auxiliary/cui.xsd)

## Cardinality

The following is a list of CUI elements and the sub-elements that they contain, with minOccurs and maxOccurs noted for each.

### cui:DocumentMarkingMetdata (type cui:DocumentMarkingMetadataType)

- cui:SpecifiedCategoryMarkingCode (0, unbounded)
- cui:BasicCategoryMarkingCode (0, unbounded)
- cui:LDCMarking (0, unbounded)
- cui:DesignatingEntityText (1, unbounded)
- cui:DecontrolSchedule (0, 1)
- cui:RequiredIndicatorsText (0, unbounded)
- cui:SupplementalAdministrativeMarkingAbstract (0, unbounded)

### cui:PortionMarkingMetadata (type cui:PortionMarkingMetadataType)

- cui:SpecifiedCategoryMarkingCode  (0, unbounded)
- cui:BasicCategoryMarkingCode (0, unbounded)
- cui:LDCMarking (0, unbounded)

### cui:LDCMarking (type cui:LDCType)

- cui:LDCCode (1, 1)
- cui:LDCForeignDisclosureToAbstract (0, unbounded)
- cui:LDC-DLONLYText (0, unbounded)
- cui:LDCAugmentationPoint (0, unbounded)

### cui:DecontrolSchedule (type cui:DecontrolScheduleType)

- cui:DecontrolDate (0, 1)
- cui:DecontrolEvent (0, 1)
- cui:DecontrolContactInformation (0, unbounded)
- cui:DecontrolScheduleAugmentationPoint (0, unbounded)

Hope this helps!

**Comment by myergens** [comment]
Thank you very much for the response!
Sincerely,
-David Y.

_________________________________
David Yergensen
AFDP Data Management Lead
Analytical Mechanics Associates

t.   661 276-2388 (w)   661-789-7307 (c)
e.  michael.d.yergensen@ama-inc.com<mailto:michael.d.yergensen@ama-inc.com>
e.  michael.d.yergensen@nasa.gov<mailto:michael.d.yergensen@nasa.gov>
w.  www.ama-inc.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.ama-2Dinc.com_&d=DwMFAg&c=ApwzowJNAKKw3xye91w7BE1XMRKi2LN9kiMk5Csz9Zk&r=G_qsq6L5HZWJMfjOGNIi0kYjuNQ8x7pjietsFjrDYTo&m=1FHpZGXQnLi37x3wDs9c6K3hjjZOmtArJ2h8jmiW9LY&s=el1YISytKwjIq2LheyRlpYdCxKpSHM1Vn76ZYAD8OoY&e=>
a.   NASA Armstrong Flight Research Center,
      Building 4840 Room 212-09
_____________________________________

Confidentiality Notice: This e-mail is intended only for the addressee named above. It contains information that is privileged, confidential or otherwise protected from use and disclosure. If you are not the intended recipient, you are hereby notified that any review, disclosure, copying, or dissemination of this transmission, or taking of any action in reliance on its contents, or other use is strictly prohibited. If you have received this transmission in error, please reply to the sender listed above immediately and permanently delete this message from your inbox. Thank you for your cooperation.

**Comment by myergens** [comment]
Good morning,
I have some questions concerning the CUI schema and the simpleType “LDCCodeSimpleType”. 

The simpleType "LDCCodeSimpleType" contains two different types of CVEs.  
•	Some of the CVEs are for use only with "DocumentMarkingMetadata"
          o	Attorney-Client, Attorney-WP, Deliberative, DISPLAY ONLY, NOFORN 
•	Some of the CVEs are for use only with "PortionMarkingMetadata"
          o	AC, AWP, DELIB, DL ONLY, NF, 
•	Other CVEs may be used in both
          o	FED ONLY. FEDCON, NOCON, REL TO

By having all of these values defined in a single simpleType, the only way to perform accurate validation is thru the use of Schematron rules.
Would you consider separating these into two separate simpleTypes?
•	one that only contained the permissible CVEs for LDCCode within the "DocumentMarkingMetadata" structure?
•	and one that only contained the permissible CVEs for LDCCode within the "PortionMarkingMetadata" structure?

I’m also curious as to why some values are in ALL CAPS, while others are in mixed-case.
Thanks in advance.
Sincerely,
David Yergensen (Michael.d.yergensen@nasa.gov)

**Comment by cdmgtri** [comment]
We will be able to split the combined code set into two separate code sets because that is a better representation of the requirements.  That should appear in NIEM 5.1 release candidate 1.  

It's a good question, but we don't have an answer about the reason for the capitalization differences other than NIEM isn't the authoritative source for the code set and we have to use the codes and definitions as they are provided.

Thanks for the feedback!
