### ISSUE TITLE
Host Alternative Formats

### ISSUE THREAD

**Issue by TJKoury** [NIEM/NIEM-Releases#3]
Please host the alternative formats in the NIEM/NIEM-Releases repo as well, would be very helpful for developers.

The alternative formats are tools to allow developers to programmatically understand and utilize the complex schema relationships within NIEM.

For example, understanding that a message is an external schema (appinfo:externalAdapterTypeIndicator) corresponds to 'true' in the NamespaceIsExternallyGenerated column in the Namespace worksheet, as well as a lack of a VersionURI.

**Comment by TJKoury** [comment]
This is answered by the maintain-niem branch.  Would be helpful (and cleaner) if everything was in the same branch with each release; separating formats into different branches just makes things harder from a dependency standpoint.

**Comment by webb** [comment]
I refactored a bit; for now, the maintain-niem-4.0 branch is just another name for the master branch (which won't be the case when 4.1 comes out). Look OK?

I don't know what "if everything was in the same branch with each release). Are you talking about the dev branches that were supporting development of the alternate formats and the JSONLD context? Right now they're just commits on the master branch.

Lemme know.

**Comment by TJKoury** [comment]
Looks good, but a few additional things:

1.  Please remove versioning in the file directory (csv/niem-4.0  should be just /csv/niem).  Branches and tags should be used for versioning so that developers don't have to rewrite paths every time there is a version update.

2.  Please consider uploading the complete schema documents (like niem.xlsx in the download that has all the workbooks), this will also help developers not having to import several files if they don't want to.   A case could certainly be made to keep the files separate to reduce the memory footprint for people to import the data.

**Comment by TJKoury** [comment]
Also, I don't see the xlsx formats at all, having those would be helpful.

**Comment by cdmgtri** [comment]
NIEM 5.0 has removed version numbers from folders.  Schemas and CSVs will appear under the same path going forward.  The documentation spreadsheets kept the version numbers in the file names because those aren't expected to be processed programmatically and because Excel will not open two spreadsheets with the same file name (different paths) at the same time.

The developers spreadsheet was discontinued because it carried the same data as the NIEM CSVs and we were trying to keep the package size from getting any bigger than it needed to be.

Thanks!
