### ISSUE TITLE
Create nc:PersonIdentification as substitution head for all nc:PersonXXXIdentification elements

### ISSUE THREAD

**Issue by DonClysdale** [NIEM/NIEM-Releases#74]
Adding additional Identification elements is adding to nc:PersonType "sprawl". It would be cleaner to add one nc:IdentificationType element, say nc:PersonIdentification to the nc:PersonType sequence and add all the other nc:PersonXXXIdentification elements to that substitutionGroup and remove them from nc:PersonType.

e.g. <xs:element name="nc:PersonHumanResourceIdentification" substitutionGroup="nc:PersonIdentification"/>

same for:
nc:PersonLicenseIdentification
nc:PersonNationalIdentification
nc:PersonOtherIdentification
nc:PersonPassportIdentification
nc:PersonSSNIdentification
nc:PersonStateIdentification
nc:PersonTaxIdentification
and the newly added nc:PersonMilitaryIdentification

**Comment by cdmgtri** [comment]
The Harmonization Workgroup decided not to recommend this proposal due to the need to set specific cardinality constraints for the affected elements that would be moved to substitution groups (e.g., make the SSN element required).  See #88 for further discussion on ways to address sprawl in the model.
